# 1. Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
---
# 2. ConfigMap (Dinamik İçerik)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.configMapName }}
  namespace: {{ .Values.global.namespace }}
data:
{{- range $key, $value := .Values.configData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
---
# 3. Secret (Otomatik Base64 Dönüşümü)
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secretName }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.secretData }}
  # Helm'in b64enc fonksiyonu sayesinde şifreyi values'a düz metin yazsan da 
  # buraya base64 olarak basılır.
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
---
# 4. PersistentVolume (Cluster Genelinde)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.db.persistence.pvName | default "postgres-pv" }}
spec:
  capacity:
    storage: {{ .Values.db.persistence.storage | default "1Gi" }}
  accessModes:
    - {{ .Values.db.persistence.accessMode | default "ReadWriteOnce" }}
  hostPath:
    path: {{ .Values.db.persistence.hostPath | quote }}
---
# 5. PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.db.persistence.pvcName }}
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - {{ .Values.db.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.db.persistence.storage | default "1Gi" }}

# 6. Prometheus
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.global.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # 15 saniyede bir veri topla

    scrape_configs:
      # Kubernetes Node verilerini (CPU/RAM) toplamak için
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)

      # Podlarin içindeki metrikleri toplamak için
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
