apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: todo-app-updater
  namespace: argocd
spec:
  # Sadece temel alanları bırakıyoruz
  image: harbor.bilgem.tubitak.gov.tr/tmp/todo-frontend
  updateStrategy: latest
