apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deploymentName }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backend.appName }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080" # veya 8080 (backend için)
      labels:
        app: {{ .Values.backend.appName }}
    spec:
      containers:
      - name: backend
        image: "{{ .Values.backend.image }}:{{ .Values.backend.imageTag }}"
        imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
        envFrom:
        - configMapRef: 
            name: {{ .Values.global.configMapName }}
        - secretRef: 
            name: {{ .Values.global.secretName }}
        env:
        - name: DB_HOST
          value: {{ .Values.backend.env.dbHost | quote }}
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.serviceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.backend.appName }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
  type: {{ .Values.backend.service.type }}
