# 1. Deployment Bölümü
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deploymentName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.frontend.appName }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80" # veya 8080 (backend için)
      labels:
        app: {{ .Values.frontend.appName }}
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image }}:{{ .Values.frontend.imageTag }}"
        imagePullPolicy: {{ .Values.frontend.pullPolicy | default "Always" }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort | default 80 }}
        resources:
          requests:
            cpu: {{ .Values.frontend.cpuRequest | default "250m" }}
            memory: {{ .Values.frontend.memoryRequest | default "128Mi" }}
          limits:
            cpu: {{ .Values.frontend.cpuLimits | default "500m" }}
            memory: {{ .Values.frontend.memoryLimits | default "256Mi" }}
---
# 2. Service Bölümü
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.frontend.appName }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    nodePort: {{ .Values.frontend.service.nodePort }}
    
