# 1. Prometheus Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.prometheus.deploymentName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.prometheus.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.prometheus.appName }}
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest  # Prometheus'un resmi Docker imajı kullanılıyor.
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"  # ConfigMap ile sağlanan yapılandırma dosyası belirtiliyor.
        ports:
        - containerPort: 9090  # Prometheus web arayüzü için kullanılan port.
        volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus  # ConfigMap içeriğinin bağlandığı dizin.
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config  # ConfigMap kullanılarak yapılandırma dosyası bağlanıyor.
---
# 2. Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.serviceName }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: {{ .Values.prometheus.appName }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    targetPort: {{ .Values.prometheus.service.targetPort }}
    nodePort: {{ .Values.prometheus.service.nodePort }}
---
# 3. Prometheus ConfigMap
# 3. Prometheus ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: {{ .Values.global.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # ASIL RAM VERİSİ BURADAN GELECEK 
      - job_name: 'kubernetes-cadvisor'
        scheme: https
        metrics_path: /metrics/cadvisor
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node

      # POD'ların kendi metrikleri (Eğer exporter olsaydi buradan gelirdi)
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          # HATA ÇÖZÜCÜ: Adresi IP:PORT formatina getirir (lookup 80 hatasini çözer)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
